# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panconvert_diag_prefpane.ui'
#
# Created: Sun May 10 13:24:18 2015
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.resize(655, 357)
        DialogPreferences.setMinimumSize(QtCore.QSize(400, 100))
        self.BoxFromFormat = QtWidgets.QGroupBox(DialogPreferences)
        self.BoxFromFormat.setGeometry(QtCore.QRect(40, 150, 131, 121))
        self.BoxFromFormat.setObjectName("BoxFromFormat")
        self.ButtonFromHtml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromHtml.setGeometry(QtCore.QRect(20, 30, 102, 20))
        self.ButtonFromHtml.setObjectName("ButtonFromHtml")
        self.ButtonFromLatex = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromLatex.setGeometry(QtCore.QRect(20, 50, 102, 20))
        self.ButtonFromLatex.setObjectName("ButtonFromLatex")
        self.ButtonFromMarkdown = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromMarkdown.setGeometry(QtCore.QRect(20, 70, 102, 20))
        self.ButtonFromMarkdown.setObjectName("ButtonFromMarkdown")
        self.ButtonFromOpml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromOpml.setGeometry(QtCore.QRect(20, 90, 102, 20))
        self.ButtonFromOpml.setObjectName("ButtonFromOpml")
        self.BoxToFormat = QtWidgets.QGroupBox(DialogPreferences)
        self.BoxToFormat.setGeometry(QtCore.QRect(210, 150, 111, 141))
        self.BoxToFormat.setObjectName("BoxToFormat")
        self.ButtonToHtml = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToHtml.setGeometry(QtCore.QRect(10, 30, 102, 20))
        self.ButtonToHtml.setObjectName("ButtonToHtml")
        self.ButtonToLatex = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToLatex.setGeometry(QtCore.QRect(10, 50, 102, 20))
        self.ButtonToLatex.setObjectName("ButtonToLatex")
        self.ButtonToMarkdown = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToMarkdown.setGeometry(QtCore.QRect(10, 70, 102, 20))
        self.ButtonToMarkdown.setObjectName("ButtonToMarkdown")
        self.ButtonToOpml = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToOpml.setGeometry(QtCore.QRect(10, 90, 102, 20))
        self.ButtonToOpml.setObjectName("ButtonToOpml")
        self.ButtonToLyx = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToLyx.setGeometry(QtCore.QRect(10, 110, 102, 20))
        self.ButtonToLyx.setObjectName("ButtonToLyx")
        self.groupBox = QtWidgets.QGroupBox(DialogPreferences)
        self.groupBox.setGeometry(QtCore.QRect(370, 150, 231, 161))
        self.groupBox.setObjectName("groupBox")
        self.XtraParameter = QtWidgets.QLineEdit(self.groupBox)
        self.XtraParameter.setGeometry(QtCore.QRect(80, 100, 113, 21))
        self.XtraParameter.setObjectName("XtraParameter")
        self.FromParameter = QtWidgets.QLineEdit(self.groupBox)
        self.FromParameter.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.FromParameter.setObjectName("FromParameter")
        self.ToParameter = QtWidgets.QLineEdit(self.groupBox)
        self.ToParameter.setGeometry(QtCore.QRect(80, 70, 113, 21))
        self.ToParameter.setObjectName("ToParameter")
        self.label_FromParameter = QtWidgets.QLabel(self.groupBox)
        self.label_FromParameter.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_FromParameter.setObjectName("label_FromParameter")
        self.label_ToParameter = QtWidgets.QLabel(self.groupBox)
        self.label_ToParameter.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.label_ToParameter.setObjectName("label_ToParameter")
        self.label_Parameter = QtWidgets.QLabel(self.groupBox)
        self.label_Parameter.setGeometry(QtCore.QRect(10, 100, 62, 16))
        self.label_Parameter.setObjectName("label_Parameter")
        self.layoutWidget = QtWidgets.QWidget(DialogPreferences)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 300, 316, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonSave = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonSave.setObjectName("ButtonSave")
        self.horizontalLayout.addWidget(self.ButtonSave)
        self.ButtonCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.horizontalLayout.addWidget(self.ButtonCancel)
        self.StandardConversion = QtWidgets.QCheckBox(self.layoutWidget)
        self.StandardConversion.setChecked(False)
        self.StandardConversion.setObjectName("StandardConversion")
        self.horizontalLayout.addWidget(self.StandardConversion)
        self.layoutWidget1 = QtWidgets.QWidget(DialogPreferences)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 20, 381, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pandoc_Path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Pandoc_Path.setText("")
        self.Pandoc_Path.setObjectName("Pandoc_Path")
        self.verticalLayout.addWidget(self.Pandoc_Path)
        self.Markdown_Path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Markdown_Path.setText("")
        self.Markdown_Path.setObjectName("Markdown_Path")
        self.verticalLayout.addWidget(self.Markdown_Path)
        self.Dialog_Path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Dialog_Path.setObjectName("Dialog_Path")
        self.verticalLayout.addWidget(self.Dialog_Path)
        self.layoutWidget2 = QtWidgets.QWidget(DialogPreferences)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 20, 159, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Pandoc_Path = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Pandoc_Path.setObjectName("label_Pandoc_Path")
        self.verticalLayout_2.addWidget(self.label_Pandoc_Path)
        self.label_Markdown_Path = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Markdown_Path.sizePolicy().hasHeightForWidth())
        self.label_Markdown_Path.setSizePolicy(sizePolicy)
        self.label_Markdown_Path.setObjectName("label_Markdown_Path")
        self.verticalLayout_2.addWidget(self.label_Markdown_Path)
        self.label_Dialog_Path = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Dialog_Path.setObjectName("label_Dialog_Path")
        self.verticalLayout_2.addWidget(self.label_Dialog_Path)

        self.retranslateUi(DialogPreferences)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "Preferences"))
        self.BoxFromFormat.setTitle(_translate("DialogPreferences", "Default From"))
        self.ButtonFromHtml.setText(_translate("DialogPreferences", "HTML"))
        self.ButtonFromLatex.setText(_translate("DialogPreferences", "Latex"))
        self.ButtonFromMarkdown.setText(_translate("DialogPreferences", "Markdown"))
        self.ButtonFromOpml.setText(_translate("DialogPreferences", "Opml"))
        self.BoxToFormat.setTitle(_translate("DialogPreferences", "Default To"))
        self.ButtonToHtml.setText(_translate("DialogPreferences", "HTML"))
        self.ButtonToLatex.setText(_translate("DialogPreferences", "Latex"))
        self.ButtonToMarkdown.setText(_translate("DialogPreferences", "Markdown"))
        self.ButtonToOpml.setText(_translate("DialogPreferences", "Opml"))
        self.ButtonToLyx.setText(_translate("DialogPreferences", "Lyx"))
        self.groupBox.setTitle(_translate("DialogPreferences", "Manual Converter Defaults"))
        self.XtraParameter.setPlaceholderText(_translate("DialogPreferences", "-o filename.odt"))
        self.FromParameter.setPlaceholderText(_translate("DialogPreferences", "markdown"))
        self.ToParameter.setPlaceholderText(_translate("DialogPreferences", "odt"))
        self.label_FromParameter.setText(_translate("DialogPreferences", "From"))
        self.label_ToParameter.setText(_translate("DialogPreferences", "To"))
        self.label_Parameter.setText(_translate("DialogPreferences", "Parameter"))
        self.ButtonSave.setText(_translate("DialogPreferences", "Save"))
        self.ButtonCancel.setText(_translate("DialogPreferences", "Cancel"))
        self.StandardConversion.setText(_translate("DialogPreferences", "Standard Conversion"))
        self.Pandoc_Path.setPlaceholderText(_translate("DialogPreferences", "/usr/local/bin/pandoc"))
        self.Markdown_Path.setPlaceholderText(_translate("DialogPreferences", "/usr/local/bin/multimarkdown"))
        self.Dialog_Path.setPlaceholderText(_translate("DialogPreferences", "/Users"))
        self.label_Pandoc_Path.setText(_translate("DialogPreferences", "Path to Pandoc Binary"))
        self.label_Markdown_Path.setText(_translate("DialogPreferences", "Path to Markdown Binary"))
        self.label_Dialog_Path.setText(_translate("DialogPreferences", "Open / Save - Path"))

