# Form implementation generated from reading ui file 'source/gui/panconvert_diag_toformat.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_To_Format_Dialog(object):
    def setupUi(self, To_Format_Dialog):
        To_Format_Dialog.setObjectName("To_Format_Dialog")
        To_Format_Dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        To_Format_Dialog.setEnabled(True)
        To_Format_Dialog.resize(334, 402)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(To_Format_Dialog.sizePolicy().hasHeightForWidth())
        To_Format_Dialog.setSizePolicy(sizePolicy)
        To_Format_Dialog.setMinimumSize(QtCore.QSize(250, 280))
        To_Format_Dialog.setSizeGripEnabled(False)
        To_Format_Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(To_Format_Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchInput = QtWidgets.QLineEdit(parent=To_Format_Dialog)
        self.searchInput.setObjectName("searchInput")
        self.searchLayout.addWidget(self.searchInput)
        self.searchClearButton = QtWidgets.QPushButton(parent=To_Format_Dialog)
        self.searchClearButton.setObjectName("searchClearButton")
        self.searchLayout.addWidget(self.searchClearButton)
        self.verticalLayout.addLayout(self.searchLayout)
        self.formatList = QtWidgets.QListWidget(parent=To_Format_Dialog)
        self.formatList.setMinimumSize(QtCore.QSize(200, 100))
        self.formatList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.formatList.setAlternatingRowColors(True)
        self.formatList.setObjectName("formatList")
        self.verticalLayout.addWidget(self.formatList)
        self.ButtonCancel = QtWidgets.QPushButton(parent=To_Format_Dialog)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.verticalLayout.addWidget(self.ButtonCancel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(To_Format_Dialog)
        QtCore.QMetaObject.connectSlotsByName(To_Format_Dialog)

    def retranslateUi(self, To_Format_Dialog):
        _translate = QtCore.QCoreApplication.translate
        To_Format_Dialog.setWindowTitle(_translate("To_Format_Dialog", "Pandoc To Formats"))
        self.searchInput.setPlaceholderText(_translate("To_Format_Dialog", "Search formats..."))
        self.searchClearButton.setText(_translate("To_Format_Dialog", "Clear"))
        self.ButtonCancel.setText(_translate("To_Format_Dialog", "Cancel"))
