# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panconvert_gui.ui'
#
# Created: Sat Dec  6 23:09:27 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_notepad(object):
    def setupUi(self, notepad):
        notepad.setObjectName("notepad")
        notepad.resize(710, 579)
        self.centralwidget = QtWidgets.QWidget(notepad)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(710, 500))
        self.centralwidget.setBaseSize(QtCore.QSize(710, 700))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.BoxFromFormat = QtWidgets.QGroupBox(self.centralwidget)
        self.BoxFromFormat.setMinimumSize(QtCore.QSize(140, 120))
        self.BoxFromFormat.setMaximumSize(QtCore.QSize(140, 100))
        self.BoxFromFormat.setObjectName("BoxFromFormat")
        self.ButtonFromHtml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromHtml.setGeometry(QtCore.QRect(20, 30, 56, 20))
        self.ButtonFromHtml.setObjectName("ButtonFromHtml")
        self.ButtonFromLatex = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromLatex.setGeometry(QtCore.QRect(20, 49, 60, 20))
        self.ButtonFromLatex.setObjectName("ButtonFromLatex")
        self.ButtonFromMarkdown = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromMarkdown.setGeometry(QtCore.QRect(20, 68, 91, 20))
        self.ButtonFromMarkdown.setChecked(False)
        self.ButtonFromMarkdown.setObjectName("ButtonFromMarkdown")
        self.ButtonFromOpml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromOpml.setGeometry(QtCore.QRect(20, 87, 60, 20))
        self.ButtonFromOpml.setCheckable(True)
        self.ButtonFromOpml.setChecked(False)
        self.ButtonFromOpml.setObjectName("ButtonFromOpml")
        self.gridLayout_4.addWidget(self.BoxFromFormat, 0, 0, 1, 1)
        self.BoxToFormat = QtWidgets.QGroupBox(self.centralwidget)
        self.BoxToFormat.setMinimumSize(QtCore.QSize(140, 135))
        self.BoxToFormat.setMaximumSize(QtCore.QSize(140, 135))
        self.BoxToFormat.setObjectName("BoxToFormat")
        self.layoutWidget = QtWidgets.QWidget(self.BoxToFormat)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 31, 92, 96))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ButtonToLatex = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonToLatex.setObjectName("ButtonToLatex")
        self.gridLayout.addWidget(self.ButtonToLatex, 0, 0, 1, 1)
        self.ButtonToOpml = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonToOpml.setObjectName("ButtonToOpml")
        self.gridLayout.addWidget(self.ButtonToOpml, 1, 0, 1, 1)
        self.ButtonToMarkdown = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonToMarkdown.setCheckable(True)
        self.ButtonToMarkdown.setChecked(False)
        self.ButtonToMarkdown.setObjectName("ButtonToMarkdown")
        self.gridLayout.addWidget(self.ButtonToMarkdown, 2, 0, 1, 1)
        self.ButtonToHtml = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonToHtml.setChecked(False)
        self.ButtonToHtml.setObjectName("ButtonToHtml")
        self.gridLayout.addWidget(self.ButtonToHtml, 3, 0, 1, 1)
        self.ButtonToLyx = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonToLyx.setObjectName("ButtonToLyx")
        self.gridLayout.addWidget(self.ButtonToLyx, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.BoxToFormat, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelFromBox = QtWidgets.QLabel(self.centralwidget)
        self.labelFromBox.setObjectName("labelFromBox")
        self.gridLayout_2.addWidget(self.labelFromBox, 0, 0, 1, 1)
        self.FromParameter = QtWidgets.QLineEdit(self.centralwidget)
        self.FromParameter.setInputMask("")
        self.FromParameter.setText("")
        self.FromParameter.setClearButtonEnabled(True)
        self.FromParameter.setObjectName("FromParameter")
        self.gridLayout_2.addWidget(self.FromParameter, 0, 1, 1, 1)
        self.labelToBox = QtWidgets.QLabel(self.centralwidget)
        self.labelToBox.setObjectName("labelToBox")
        self.gridLayout_2.addWidget(self.labelToBox, 1, 0, 1, 1)
        self.ToParameter = QtWidgets.QLineEdit(self.centralwidget)
        self.ToParameter.setText("")
        self.ToParameter.setClearButtonEnabled(True)
        self.ToParameter.setObjectName("ToParameter")
        self.gridLayout_2.addWidget(self.ToParameter, 1, 1, 1, 1)
        self.labelParameter = QtWidgets.QLabel(self.centralwidget)
        self.labelParameter.setObjectName("labelParameter")
        self.gridLayout_2.addWidget(self.labelParameter, 2, 0, 1, 1)
        self.ExtraParameter = QtWidgets.QLineEdit(self.centralwidget)
        self.ExtraParameter.setText("")
        self.ExtraParameter.setClearButtonEnabled(True)
        self.ExtraParameter.setObjectName("ExtraParameter")
        self.gridLayout_2.addWidget(self.ExtraParameter, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StandardConversion = QtWidgets.QCheckBox(self.centralwidget)
        self.StandardConversion.setChecked(False)
        self.StandardConversion.setAutoRepeat(False)
        self.StandardConversion.setObjectName("StandardConversion")
        self.verticalLayout_3.addWidget(self.StandardConversion)
        self.ButtonConvert = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonConvert.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ButtonConvert.setObjectName("ButtonConvert")
        self.verticalLayout_3.addWidget(self.ButtonConvert)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.editor_window = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.editor_window.setObjectName("editor_window")
        self.gridLayout_4.addWidget(self.editor_window, 1, 0, 1, 4)
        notepad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(notepad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 22))
        self.menubar.setAcceptDrops(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMarkdown = QtWidgets.QMenu(self.menubar)
        self.menuMarkdown.setObjectName("menuMarkdown")
        self.menuLatex = QtWidgets.QMenu(self.menubar)
        self.menuLatex.setObjectName("menuLatex")
        self.menuOpml = QtWidgets.QMenu(self.menubar)
        self.menuOpml.setObjectName("menuOpml")
        self.menuExtras = QtWidgets.QMenu(self.menubar)
        self.menuExtras.setEnabled(True)
        self.menuExtras.setObjectName("menuExtras")
        self.menuHtml = QtWidgets.QMenu(self.menubar)
        self.menuHtml.setObjectName("menuHtml")
        self.menuEdit_2 = QtWidgets.QMenu(self.menubar)
        self.menuEdit_2.setObjectName("menuEdit_2")
        self.menuLyx = QtWidgets.QMenu(self.menubar)
        self.menuLyx.setObjectName("menuLyx")
        notepad.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(notepad)
        self.statusbar.setObjectName("statusbar")
        notepad.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(notepad)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setObjectName("toolBar")
        notepad.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(notepad)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(notepad)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_AS = QtWidgets.QAction(notepad)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save_as"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_AS.setIcon(icon2)
        self.actionSave_AS.setObjectName("actionSave_AS")
        self.actionNew = QtWidgets.QAction(notepad)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/new"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionMarkdown2Latex = QtWidgets.QAction(notepad)
        self.actionMarkdown2Latex.setObjectName("actionMarkdown2Latex")
        self.actionOpml2latex = QtWidgets.QAction(notepad)
        self.actionOpml2latex.setObjectName("actionOpml2latex")
        self.actionOpml2Markdown = QtWidgets.QAction(notepad)
        self.actionOpml2Markdown.setObjectName("actionOpml2Markdown")
        self.actionMarkdown2opml = QtWidgets.QAction(notepad)
        self.actionMarkdown2opml.setObjectName("actionMarkdown2opml")
        self.actionPreferences = QtWidgets.QAction(notepad)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/freferences"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon4)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionLatex2Opml = QtWidgets.QAction(notepad)
        self.actionLatex2Opml.setObjectName("actionLatex2Opml")
        self.actionLatex2Markdown = QtWidgets.QAction(notepad)
        self.actionLatex2Markdown.setObjectName("actionLatex2Markdown")
        self.actionHtml2Markdown = QtWidgets.QAction(notepad)
        self.actionHtml2Markdown.setObjectName("actionHtml2Markdown")
        self.actionHtml2Latex = QtWidgets.QAction(notepad)
        self.actionHtml2Latex.setObjectName("actionHtml2Latex")
        self.actionHtml2opml = QtWidgets.QAction(notepad)
        self.actionHtml2opml.setObjectName("actionHtml2opml")
        self.actionOpml2html = QtWidgets.QAction(notepad)
        self.actionOpml2html.setObjectName("actionOpml2html")
        self.actionMarkdown2html = QtWidgets.QAction(notepad)
        self.actionMarkdown2html.setObjectName("actionMarkdown2html")
        self.actionLatex2html = QtWidgets.QAction(notepad)
        self.actionLatex2html.setObjectName("actionLatex2html")
        self.actionHelp = QtWidgets.QAction(notepad)
        self.actionHelp.setObjectName("actionHelp")
        self.actionMarkdown2Lyx = QtWidgets.QAction(notepad)
        self.actionMarkdown2Lyx.setObjectName("actionMarkdown2Lyx")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_AS)
        self.menuFile.addSeparator()
        self.menuMarkdown.addAction(self.actionOpml2Markdown)
        self.menuMarkdown.addAction(self.actionLatex2Markdown)
        self.menuMarkdown.addAction(self.actionHtml2Markdown)
        self.menuLatex.addAction(self.actionMarkdown2Latex)
        self.menuLatex.addAction(self.actionOpml2latex)
        self.menuLatex.addAction(self.actionHtml2Latex)
        self.menuOpml.addAction(self.actionMarkdown2opml)
        self.menuOpml.addAction(self.actionLatex2Opml)
        self.menuOpml.addAction(self.actionHtml2opml)
        self.menuExtras.addAction(self.actionHelp)
        self.menuHtml.addAction(self.actionMarkdown2html)
        self.menuHtml.addAction(self.actionOpml2html)
        self.menuHtml.addAction(self.actionLatex2html)
        self.menuEdit_2.addAction(self.actionPreferences)
        self.menuLyx.addAction(self.actionMarkdown2Lyx)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit_2.menuAction())
        self.menubar.addAction(self.menuMarkdown.menuAction())
        self.menubar.addAction(self.menuLatex.menuAction())
        self.menubar.addAction(self.menuOpml.menuAction())
        self.menubar.addAction(self.menuHtml.menuAction())
        self.menubar.addAction(self.menuLyx.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_AS)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPreferences)

        self.retranslateUi(notepad)
        QtCore.QMetaObject.connectSlotsByName(notepad)

    def retranslateUi(self, notepad):
        _translate = QtCore.QCoreApplication.translate
        notepad.setWindowTitle(_translate("notepad", "PanConvert"))
        self.BoxFromFormat.setTitle(_translate("notepad", "From Format"))
        self.ButtonFromHtml.setText(_translate("notepad", "Html"))
        self.ButtonFromLatex.setText(_translate("notepad", "Latex"))
        self.ButtonFromMarkdown.setText(_translate("notepad", "Markdown"))
        self.ButtonFromOpml.setText(_translate("notepad", "Opml"))
        self.BoxToFormat.setTitle(_translate("notepad", "To Format"))
        self.ButtonToLatex.setText(_translate("notepad", "Latex"))
        self.ButtonToOpml.setText(_translate("notepad", "Opml"))
        self.ButtonToMarkdown.setText(_translate("notepad", "Markdown"))
        self.ButtonToHtml.setText(_translate("notepad", "Html"))
        self.ButtonToLyx.setText(_translate("notepad", "Lyx"))
        self.labelFromBox.setText(_translate("notepad", "From"))
        self.labelToBox.setText(_translate("notepad", "To"))
        self.labelParameter.setText(_translate("notepad", "Parameter"))
        self.StandardConversion.setText(_translate("notepad", "Standard"))
        self.ButtonConvert.setText(_translate("notepad", "Convert"))
        self.menuFile.setTitle(_translate("notepad", "File"))
        self.menuMarkdown.setTitle(_translate("notepad", "Markdown"))
        self.menuLatex.setTitle(_translate("notepad", "Latex"))
        self.menuOpml.setTitle(_translate("notepad", "Opml"))
        self.menuExtras.setTitle(_translate("notepad", "Help"))
        self.menuHtml.setTitle(_translate("notepad", "Html"))
        self.menuEdit_2.setTitle(_translate("notepad", "Edit"))
        self.menuLyx.setTitle(_translate("notepad", "Lyx"))
        self.toolBar.setWindowTitle(_translate("notepad", "toolBar"))
        self.actionSave.setText(_translate("notepad", "Save"))
        self.actionOpen.setText(_translate("notepad", "Open"))
        self.actionOpen.setShortcut(_translate("notepad", "Ctrl+O"))
        self.actionSave_AS.setText(_translate("notepad", "Save AS"))
        self.actionSave_AS.setShortcut(_translate("notepad", "Ctrl+S"))
        self.actionNew.setText(_translate("notepad", "New"))
        self.actionNew.setToolTip(_translate("notepad", "New"))
        self.actionMarkdown2Latex.setText(_translate("notepad", "Markdown2Latex"))
        self.actionOpml2latex.setText(_translate("notepad", "opml2latex"))
        self.actionOpml2latex.setToolTip(_translate("notepad", "Opml2Latex"))
        self.actionOpml2Markdown.setText(_translate("notepad", "Opml2Markdown"))
        self.actionOpml2Markdown.setToolTip(_translate("notepad", "Opml2Markdown(Pandoc)"))
        self.actionMarkdown2opml.setText(_translate("notepad", "Markdown2opml"))
        self.actionPreferences.setText(_translate("notepad", "Preferences"))
        self.actionLatex2Opml.setText(_translate("notepad", "Latex2Opml"))
        self.actionLatex2Markdown.setText(_translate("notepad", "Latex2Markdown"))
        self.actionHtml2Markdown.setText(_translate("notepad", "Html2Markdown"))
        self.actionHtml2Latex.setText(_translate("notepad", "Html2Latex"))
        self.actionHtml2opml.setText(_translate("notepad", "html2opml"))
        self.actionOpml2html.setText(_translate("notepad", "opml2html"))
        self.actionMarkdown2html.setText(_translate("notepad", "markdown2html"))
        self.actionLatex2html.setText(_translate("notepad", "latex2html"))
        self.actionHelp.setText(_translate("notepad", "Help"))
        self.actionMarkdown2Lyx.setText(_translate("notepad", "Markdown2Lyx"))

import source.gui.icons_rc
