# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panconvert_dialog_batch.ui'
#
# Created: Thu Feb 23 12:47:05 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogBatch(object):
    def setupUi(self, DialogBatch):
        DialogBatch.setObjectName("DialogBatch")
        DialogBatch.resize(386, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogBatch.sizePolicy().hasHeightForWidth())
        DialogBatch.setSizePolicy(sizePolicy)
        DialogBatch.setMinimumSize(QtCore.QSize(386, 250))
        DialogBatch.setMaximumSize(QtCore.QSize(386, 250))
        self.ButtonSave = QtWidgets.QPushButton(DialogBatch)
        self.ButtonSave.setGeometry(QtCore.QRect(250, 200, 114, 32))
        self.ButtonSave.setObjectName("ButtonSave")
        self.ButtonCancel = QtWidgets.QPushButton(DialogBatch)
        self.ButtonCancel.setGeometry(QtCore.QRect(250, 160, 114, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonCancel.sizePolicy().hasHeightForWidth())
        self.ButtonCancel.setSizePolicy(sizePolicy)
        self.ButtonCancel.setMinimumSize(QtCore.QSize(114, 32))
        self.ButtonCancel.setMaximumSize(QtCore.QSize(114, 32))
        self.ButtonCancel.setBaseSize(QtCore.QSize(114, 32))
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.Filter = QtWidgets.QLineEdit(DialogBatch)
        self.Filter.setGeometry(QtCore.QRect(10, 100, 350, 21))
        self.Filter.setObjectName("Filter")
        self.groupBox = QtWidgets.QGroupBox(DialogBatch)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 200, 100))
        self.groupBox.setMinimumSize(QtCore.QSize(200, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ParameterBatchconvertRecursive = QtWidgets.QCheckBox(self.groupBox)
        self.ParameterBatchconvertRecursive.setChecked(True)
        self.ParameterBatchconvertRecursive.setObjectName("ParameterBatchconvertRecursive")
        self.gridLayout_2.addWidget(self.ParameterBatchconvertRecursive, 3, 0, 1, 1)
        self.ParameterBatchconvertDirectory = QtWidgets.QRadioButton(self.groupBox)
        self.ParameterBatchconvertDirectory.setChecked(True)
        self.ParameterBatchconvertDirectory.setObjectName("ParameterBatchconvertDirectory")
        self.gridLayout_2.addWidget(self.ParameterBatchconvertDirectory, 2, 0, 1, 1)
        self.ParameterBatchconvertFiles = QtWidgets.QRadioButton(self.groupBox)
        self.ParameterBatchconvertFiles.setObjectName("ParameterBatchconvertFiles")
        self.gridLayout_2.addWidget(self.ParameterBatchconvertFiles, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(DialogBatch)
        self.widget.setGeometry(QtCore.QRect(10, 12, 27, 54))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_Open_Path = QtWidgets.QToolButton(self.widget)
        self.Button_Open_Path.setMaximumSize(QtCore.QSize(25, 23))
        self.Button_Open_Path.setObjectName("Button_Open_Path")
        self.verticalLayout.addWidget(self.Button_Open_Path)
        self.Button_Open_Path_Output = QtWidgets.QToolButton(self.widget)
        self.Button_Open_Path_Output.setMaximumSize(QtCore.QSize(25, 23))
        self.Button_Open_Path_Output.setObjectName("Button_Open_Path_Output")
        self.verticalLayout.addWidget(self.Button_Open_Path_Output)
        self.widget1 = QtWidgets.QWidget(DialogBatch)
        self.widget1.setGeometry(QtCore.QRect(47, 12, 311, 54))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OpenPath = QtWidgets.QLineEdit(self.widget1)
        self.OpenPath.setObjectName("OpenPath")
        self.verticalLayout_2.addWidget(self.OpenPath)
        self.OpenPath_Output = QtWidgets.QLineEdit(self.widget1)
        self.OpenPath_Output.setObjectName("OpenPath_Output")
        self.verticalLayout_2.addWidget(self.OpenPath_Output)

        self.retranslateUi(DialogBatch)
        QtCore.QMetaObject.connectSlotsByName(DialogBatch)

    def retranslateUi(self, DialogBatch):
        _translate = QtCore.QCoreApplication.translate
        DialogBatch.setWindowTitle(_translate("DialogBatch", "Batch Preferences"))
        self.ButtonSave.setText(_translate("DialogBatch", "Save"))
        self.ButtonCancel.setText(_translate("DialogBatch", "Cancel"))
        self.Filter.setPlaceholderText(_translate("DialogBatch", "optional File Extension Filter (separate with ;)"))
        self.groupBox.setTitle(_translate("DialogBatch", "Conversion Mode"))
        self.ParameterBatchconvertRecursive.setText(_translate("DialogBatch", "Recursive"))
        self.ParameterBatchconvertDirectory.setText(_translate("DialogBatch", "Directory"))
        self.ParameterBatchconvertFiles.setText(_translate("DialogBatch", "Files"))
        self.Button_Open_Path.setText(_translate("DialogBatch", "..."))
        self.Button_Open_Path_Output.setText(_translate("DialogBatch", "..."))
        self.OpenPath.setPlaceholderText(_translate("DialogBatch", "Optional Directory Path"))
        self.OpenPath_Output.setPlaceholderText(_translate("DialogBatch", "Optional Directory Path"))

