# Form implementation generated from reading ui file 'source/gui/panconvert_diag_fromformat.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_From_Format_Dialog(object):
    def setupUi(self, From_Format_Dialog):
        From_Format_Dialog.setObjectName("From_Format_Dialog")
        From_Format_Dialog.resize(300, 320)
        self.gridLayout = QtWidgets.QGridLayout(From_Format_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchInput = QtWidgets.QLineEdit(parent=From_Format_Dialog)
        self.searchInput.setObjectName("searchInput")
        self.searchLayout.addWidget(self.searchInput)
        self.searchClearButton = QtWidgets.QPushButton(parent=From_Format_Dialog)
        self.searchClearButton.setObjectName("searchClearButton")
        self.searchLayout.addWidget(self.searchClearButton)
        self.verticalLayout.addLayout(self.searchLayout)
        self.formatList = QtWidgets.QListWidget(parent=From_Format_Dialog)
        self.formatList.setMinimumSize(QtCore.QSize(200, 100))
        self.formatList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.formatList.setAlternatingRowColors(True)
        self.formatList.setObjectName("formatList")
        self.verticalLayout.addWidget(self.formatList)
        self.ButtonCancel = QtWidgets.QPushButton(parent=From_Format_Dialog)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.verticalLayout.addWidget(self.ButtonCancel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(From_Format_Dialog)
        QtCore.QMetaObject.connectSlotsByName(From_Format_Dialog)

    def retranslateUi(self, From_Format_Dialog):
        _translate = QtCore.QCoreApplication.translate
        From_Format_Dialog.setWindowTitle(_translate("From_Format_Dialog", "Pandoc From Formats"))
        self.searchInput.setPlaceholderText(_translate("From_Format_Dialog", "Search formats..."))
        self.searchClearButton.setText(_translate("From_Format_Dialog", "Clear"))
        self.ButtonCancel.setText(_translate("From_Format_Dialog", "Cancel"))
