# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panconvert_diag_prefpane.ui'
#
# Created: Mon Feb 20 10:09:12 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.resize(630, 380)
        DialogPreferences.setMinimumSize(QtCore.QSize(630, 380))
        DialogPreferences.setMaximumSize(QtCore.QSize(630, 380))
        self.tabWidget = QtWidgets.QTabWidget(DialogPreferences)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 611, 361))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_standard_pref = QtWidgets.QWidget()
        self.tab_standard_pref.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tab_standard_pref.setObjectName("tab_standard_pref")
        self.groupBox = QtWidgets.QGroupBox(self.tab_standard_pref)
        self.groupBox.setGeometry(QtCore.QRect(350, 130, 231, 141))
        self.groupBox.setObjectName("groupBox")
        self.XtraParameter = QtWidgets.QLineEdit(self.groupBox)
        self.XtraParameter.setGeometry(QtCore.QRect(80, 100, 113, 21))
        self.XtraParameter.setObjectName("XtraParameter")
        self.FromParameter = QtWidgets.QLineEdit(self.groupBox)
        self.FromParameter.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.FromParameter.setObjectName("FromParameter")
        self.ToParameter = QtWidgets.QLineEdit(self.groupBox)
        self.ToParameter.setGeometry(QtCore.QRect(80, 70, 113, 21))
        self.ToParameter.setObjectName("ToParameter")
        self.label_FromParameter = QtWidgets.QLabel(self.groupBox)
        self.label_FromParameter.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_FromParameter.setObjectName("label_FromParameter")
        self.label_ToParameter = QtWidgets.QLabel(self.groupBox)
        self.label_ToParameter.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.label_ToParameter.setObjectName("label_ToParameter")
        self.label_Parameter = QtWidgets.QLabel(self.groupBox)
        self.label_Parameter.setGeometry(QtCore.QRect(10, 100, 62, 16))
        self.label_Parameter.setObjectName("label_Parameter")
        self.BoxToFormat = QtWidgets.QGroupBox(self.tab_standard_pref)
        self.BoxToFormat.setGeometry(QtCore.QRect(190, 130, 111, 141))
        self.BoxToFormat.setObjectName("BoxToFormat")
        self.ButtonToHtml = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToHtml.setGeometry(QtCore.QRect(10, 30, 102, 20))
        self.ButtonToHtml.setObjectName("ButtonToHtml")
        self.ButtonToLatex = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToLatex.setGeometry(QtCore.QRect(10, 50, 102, 20))
        self.ButtonToLatex.setObjectName("ButtonToLatex")
        self.ButtonToMarkdown = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToMarkdown.setGeometry(QtCore.QRect(10, 70, 102, 20))
        self.ButtonToMarkdown.setObjectName("ButtonToMarkdown")
        self.ButtonToOpml = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToOpml.setGeometry(QtCore.QRect(10, 90, 102, 20))
        self.ButtonToOpml.setObjectName("ButtonToOpml")
        self.ButtonToLyx = QtWidgets.QRadioButton(self.BoxToFormat)
        self.ButtonToLyx.setGeometry(QtCore.QRect(10, 110, 102, 20))
        self.ButtonToLyx.setObjectName("ButtonToLyx")
        self.ButtonPandocPath = QtWidgets.QToolButton(self.tab_standard_pref)
        self.ButtonPandocPath.setGeometry(QtCore.QRect(170, 0, 27, 23))
        self.ButtonPandocPath.setObjectName("ButtonPandocPath")
        self.layoutWidget = QtWidgets.QWidget(self.tab_standard_pref)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 0, 381, 85))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pandoc_Path = QtWidgets.QLineEdit(self.layoutWidget)
        self.Pandoc_Path.setText("")
        self.Pandoc_Path.setObjectName("Pandoc_Path")
        self.verticalLayout.addWidget(self.Pandoc_Path)
        self.Markdown_Path = QtWidgets.QLineEdit(self.layoutWidget)
        self.Markdown_Path.setText("")
        self.Markdown_Path.setObjectName("Markdown_Path")
        self.verticalLayout.addWidget(self.Markdown_Path)
        self.Dialog_Path = QtWidgets.QLineEdit(self.layoutWidget)
        self.Dialog_Path.setObjectName("Dialog_Path")
        self.verticalLayout.addWidget(self.Dialog_Path)
        self.BoxFromFormat = QtWidgets.QGroupBox(self.tab_standard_pref)
        self.BoxFromFormat.setGeometry(QtCore.QRect(20, 130, 131, 121))
        self.BoxFromFormat.setObjectName("BoxFromFormat")
        self.ButtonFromHtml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromHtml.setGeometry(QtCore.QRect(20, 30, 102, 20))
        self.ButtonFromHtml.setObjectName("ButtonFromHtml")
        self.ButtonFromLatex = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromLatex.setGeometry(QtCore.QRect(20, 50, 102, 20))
        self.ButtonFromLatex.setObjectName("ButtonFromLatex")
        self.ButtonFromMarkdown = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromMarkdown.setGeometry(QtCore.QRect(20, 70, 102, 20))
        self.ButtonFromMarkdown.setObjectName("ButtonFromMarkdown")
        self.ButtonFromOpml = QtWidgets.QRadioButton(self.BoxFromFormat)
        self.ButtonFromOpml.setGeometry(QtCore.QRect(20, 90, 102, 20))
        self.ButtonFromOpml.setObjectName("ButtonFromOpml")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_standard_pref)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 280, 561, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonSave = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ButtonSave.setObjectName("ButtonSave")
        self.horizontalLayout.addWidget(self.ButtonSave)
        self.ButtonCancel = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.horizontalLayout.addWidget(self.ButtonCancel)
        self.StandardConversion = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.StandardConversion.setChecked(False)
        self.StandardConversion.setObjectName("StandardConversion")
        self.horizontalLayout.addWidget(self.StandardConversion)
        self.BatchConversion = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.BatchConversion.setObjectName("BatchConversion")
        self.horizontalLayout.addWidget(self.BatchConversion)
        self.label_LanguageSelector = QtWidgets.QLabel(self.tab_standard_pref)
        self.label_LanguageSelector.setGeometry(QtCore.QRect(0, 100, 161, 21))
        self.label_LanguageSelector.setObjectName("label_LanguageSelector")
        self.ButtonOpenSavePath = QtWidgets.QToolButton(self.tab_standard_pref)
        self.ButtonOpenSavePath.setGeometry(QtCore.QRect(170, 60, 27, 23))
        self.ButtonOpenSavePath.setObjectName("ButtonOpenSavePath")
        self.ButtonMarkdownPath = QtWidgets.QToolButton(self.tab_standard_pref)
        self.ButtonMarkdownPath.setGeometry(QtCore.QRect(170, 30, 27, 23))
        self.ButtonMarkdownPath.setObjectName("ButtonMarkdownPath")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_standard_pref)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 159, 81))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Pandoc_Path = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_Pandoc_Path.setObjectName("label_Pandoc_Path")
        self.verticalLayout_2.addWidget(self.label_Pandoc_Path)
        self.label_Markdown_Path = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Markdown_Path.sizePolicy().hasHeightForWidth())
        self.label_Markdown_Path.setSizePolicy(sizePolicy)
        self.label_Markdown_Path.setObjectName("label_Markdown_Path")
        self.verticalLayout_2.addWidget(self.label_Markdown_Path)
        self.label_Dialog_Path = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_Dialog_Path.setObjectName("label_Dialog_Path")
        self.verticalLayout_2.addWidget(self.label_Dialog_Path)
        self.comboBoxLanguageSelector = QtWidgets.QComboBox(self.tab_standard_pref)
        self.comboBoxLanguageSelector.setGeometry(QtCore.QRect(200, 100, 381, 26))
        self.comboBoxLanguageSelector.setEditable(False)
        self.comboBoxLanguageSelector.setCurrentText("")
        self.comboBoxLanguageSelector.setObjectName("comboBoxLanguageSelector")
        self.tabWidget.addTab(self.tab_standard_pref, "")
        self.tab_size_pref = QtWidgets.QWidget()
        self.tab_size_pref.setObjectName("tab_size_pref")
        self.ButtonSave_2 = QtWidgets.QPushButton(self.tab_size_pref)
        self.ButtonSave_2.setGeometry(QtCore.QRect(10, 290, 131, 32))
        self.ButtonSave_2.setObjectName("ButtonSave_2")
        self.ButtonCancel_2 = QtWidgets.QPushButton(self.tab_size_pref)
        self.ButtonCancel_2.setGeometry(QtCore.QRect(150, 290, 130, 32))
        self.ButtonCancel_2.setObjectName("ButtonCancel_2")
        self.BoxSaveSize = QtWidgets.QGroupBox(self.tab_size_pref)
        self.BoxSaveSize.setGeometry(QtCore.QRect(400, 190, 201, 141))
        self.BoxSaveSize.setObjectName("BoxSaveSize")
        self.Window_Size = QtWidgets.QCheckBox(self.BoxSaveSize)
        self.Window_Size.setGeometry(QtCore.QRect(10, 40, 191, 20))
        self.Window_Size.setAccessibleName("")
        self.Window_Size.setObjectName("Window_Size")
        self.Dock_Size = QtWidgets.QCheckBox(self.BoxSaveSize)
        self.Dock_Size.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.Dock_Size.setObjectName("Dock_Size")
        self.Dialog_Size = QtWidgets.QCheckBox(self.BoxSaveSize)
        self.Dialog_Size.setGeometry(QtCore.QRect(10, 100, 181, 20))
        self.Dialog_Size.setObjectName("Dialog_Size")
        self.GuiSelection = QtWidgets.QGroupBox(self.tab_size_pref)
        self.GuiSelection.setGeometry(QtCore.QRect(400, 0, 201, 91))
        self.GuiSelection.setObjectName("GuiSelection")
        self.Button_NewGui = QtWidgets.QRadioButton(self.GuiSelection)
        self.Button_NewGui.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.Button_NewGui.setObjectName("Button_NewGui")
        self.Button_OldGui = QtWidgets.QRadioButton(self.GuiSelection)
        self.Button_OldGui.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.Button_OldGui.setObjectName("Button_OldGui")
        self.Tab_Selection = QtWidgets.QGroupBox(self.tab_size_pref)
        self.Tab_Selection.setGeometry(QtCore.QRect(400, 90, 201, 91))
        self.Tab_Selection.setObjectName("Tab_Selection")
        self.Tab_StandardConverter = QtWidgets.QRadioButton(self.Tab_Selection)
        self.Tab_StandardConverter.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.Tab_StandardConverter.setObjectName("Tab_StandardConverter")
        self.Tab_ManualConverter = QtWidgets.QRadioButton(self.Tab_Selection)
        self.Tab_ManualConverter.setGeometry(QtCore.QRect(10, 60, 171, 20))
        self.Tab_ManualConverter.setObjectName("Tab_ManualConverter")
        self.BatchMode = QtWidgets.QGroupBox(self.tab_size_pref)
        self.BatchMode.setGeometry(QtCore.QRect(210, 0, 181, 91))
        self.BatchMode.setObjectName("BatchMode")
        self.Hide_Batch = QtWidgets.QCheckBox(self.BatchMode)
        self.Hide_Batch.setGeometry(QtCore.QRect(0, 30, 191, 20))
        self.Hide_Batch.setObjectName("Hide_Batch")
        self.BufferSaveName = QtWidgets.QLineEdit(self.tab_size_pref)
        self.BufferSaveName.setGeometry(QtCore.QRect(180, 240, 201, 21))
        self.BufferSaveName.setObjectName("BufferSaveName")
        self.label = QtWidgets.QLabel(self.tab_size_pref)
        self.label.setGeometry(QtCore.QRect(12, 209, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_size_pref)
        self.label_2.setGeometry(QtCore.QRect(12, 240, 161, 21))
        self.label_2.setObjectName("label_2")
        self.BufferSaveSuffix = QtWidgets.QLineEdit(self.tab_size_pref)
        self.BufferSaveSuffix.setGeometry(QtCore.QRect(180, 209, 201, 21))
        self.BufferSaveSuffix.setObjectName("BufferSaveSuffix")
        self.tabWidget.addTab(self.tab_size_pref, "")

        self.retranslateUi(DialogPreferences)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxLanguageSelector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "Preferences"))
        self.tab_standard_pref.setAccessibleName(_translate("DialogPreferences", "General Preferences"))
        self.groupBox.setTitle(_translate("DialogPreferences", "Manual Converter Defaults"))
        self.XtraParameter.setPlaceholderText(_translate("DialogPreferences", "-o filename.odt"))
        self.FromParameter.setPlaceholderText(_translate("DialogPreferences", "markdown"))
        self.ToParameter.setPlaceholderText(_translate("DialogPreferences", "odt"))
        self.label_FromParameter.setText(_translate("DialogPreferences", "From"))
        self.label_ToParameter.setText(_translate("DialogPreferences", "To"))
        self.label_Parameter.setText(_translate("DialogPreferences", "Parameter"))
        self.BoxToFormat.setTitle(_translate("DialogPreferences", "Default To"))
        self.ButtonToHtml.setText(_translate("DialogPreferences", "HTML"))
        self.ButtonToLatex.setText(_translate("DialogPreferences", "Latex"))
        self.ButtonToMarkdown.setText(_translate("DialogPreferences", "Markdown"))
        self.ButtonToOpml.setText(_translate("DialogPreferences", "Opml"))
        self.ButtonToLyx.setText(_translate("DialogPreferences", "Lyx"))
        self.ButtonPandocPath.setText(_translate("DialogPreferences", "..."))
        self.Pandoc_Path.setPlaceholderText(_translate("DialogPreferences", "/usr/local/bin/pandoc"))
        self.Markdown_Path.setPlaceholderText(_translate("DialogPreferences", "/usr/local/bin/multimarkdown"))
        self.Dialog_Path.setPlaceholderText(_translate("DialogPreferences", "/Users"))
        self.BoxFromFormat.setTitle(_translate("DialogPreferences", "Default From"))
        self.ButtonFromHtml.setText(_translate("DialogPreferences", "HTML"))
        self.ButtonFromLatex.setText(_translate("DialogPreferences", "Latex"))
        self.ButtonFromMarkdown.setText(_translate("DialogPreferences", "Markdown"))
        self.ButtonFromOpml.setText(_translate("DialogPreferences", "Opml"))
        self.ButtonSave.setText(_translate("DialogPreferences", "Save"))
        self.ButtonCancel.setText(_translate("DialogPreferences", "Cancel"))
        self.StandardConversion.setText(_translate("DialogPreferences", "Standard Conversion"))
        self.BatchConversion.setText(_translate("DialogPreferences", "Batch Conversion"))
        self.label_LanguageSelector.setText(_translate("DialogPreferences", "Language Selector"))
        self.ButtonOpenSavePath.setText(_translate("DialogPreferences", "..."))
        self.ButtonMarkdownPath.setText(_translate("DialogPreferences", "..."))
        self.label_Pandoc_Path.setText(_translate("DialogPreferences", "Path to Pandoc Binary"))
        self.label_Markdown_Path.setText(_translate("DialogPreferences", "Path to Markdown Binary"))
        self.label_Dialog_Path.setText(_translate("DialogPreferences", "Open / Save - Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_standard_pref), _translate("DialogPreferences", "General Preferences"))
        self.ButtonSave_2.setText(_translate("DialogPreferences", "Save"))
        self.ButtonCancel_2.setText(_translate("DialogPreferences", "Cancel"))
        self.BoxSaveSize.setTitle(_translate("DialogPreferences", "Save Size"))
        self.Window_Size.setText(_translate("DialogPreferences", "Size of Main Window"))
        self.Dock_Size.setText(_translate("DialogPreferences", "Size of Dock Window"))
        self.Dialog_Size.setText(_translate("DialogPreferences", "Size of Dialog Window"))
        self.GuiSelection.setTitle(_translate("DialogPreferences", "Gui Selection"))
        self.Button_NewGui.setText(_translate("DialogPreferences", "New Style Gui"))
        self.Button_OldGui.setText(_translate("DialogPreferences", "Old Style Gui"))
        self.Tab_Selection.setTitle(_translate("DialogPreferences", "Tab Selection"))
        self.Tab_StandardConverter.setText(_translate("DialogPreferences", "Standard Converter"))
        self.Tab_ManualConverter.setText(_translate("DialogPreferences", "Manual Converter"))
        self.BatchMode.setTitle(_translate("DialogPreferences", "Batch Mode"))
        self.Hide_Batch.setText(_translate("DialogPreferences", "Hide Batch Mode"))
        self.label.setText(_translate("DialogPreferences", "Buffer Save Suffix"))
        self.label_2.setText(_translate("DialogPreferences", "Buffer Save Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_size_pref), _translate("DialogPreferences", "Extra Preferences"))

