# Form implementation generated from reading ui file '/Users/apaeffgen/PROG/Python/PanConvert/source/gui/panconvert_diag_toformat.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_To_Format_Dialog(object):
    def setupUi(self, To_Format_Dialog):
        To_Format_Dialog.setObjectName("To_Format_Dialog")
        To_Format_Dialog.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        To_Format_Dialog.setEnabled(True)
        To_Format_Dialog.resize(334, 402)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(To_Format_Dialog.sizePolicy().hasHeightForWidth())
        To_Format_Dialog.setSizePolicy(sizePolicy)
        To_Format_Dialog.setMinimumSize(QtCore.QSize(224, 234))
        To_Format_Dialog.setSizeGripEnabled(False)
        To_Format_Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(To_Format_Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonCancel = QtWidgets.QPushButton(parent=To_Format_Dialog)
        self.ButtonCancel.setObjectName("ButtonCancel")
        self.verticalLayout.addWidget(self.ButtonCancel)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.textBrowser = QtWebEngineWidgets.QWebEngineView(parent=To_Format_Dialog)
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(To_Format_Dialog)
        QtCore.QMetaObject.connectSlotsByName(To_Format_Dialog)

    def retranslateUi(self, To_Format_Dialog):
        _translate = QtCore.QCoreApplication.translate
        To_Format_Dialog.setWindowTitle(_translate("To_Format_Dialog", "Pandoc To Formats"))
        self.ButtonCancel.setText(_translate("To_Format_Dialog", "Cancel"))
from PyQt6 import QtWebEngineWidgets
